config/packages/assets.yaml
config/packages/translation.yaml
config/packages/twig.yaml
config/packages/webpack_encore.yaml
config/services.yaml
src/Bridge/Symfony/DependencyInjection/KernelExtension.php
src/Bridge/Symfony/Kernel.php
src/Generator.php

feat: autoregister bundle folders as Twig namespaces

---

resources/init/.gitlab-ci.yml

fix: correct the Gitlab CI config

---

src/Bridge/Symfony/Kernel.php

feat: load custom project bundles

---

src/Bridge/Symfony/Controller/DefaultController.php

feat: define a custom template to use for a route

---

config/routes/yassg.yaml
src/Generator.php

feat: dump 404 page

---

resources/init/demo/config/packages/yassg_database.yaml
resources/init/demo/templates/pages/demo.html.twig

New starter page

---

src/Database.php
src/Database/MemoryDatabase.php

Slight quality of life, Database::findOne returns only the first item.

feat: Database::findOne

---

config/services.yaml
src/Bridge/Attribute/Localized.php
src/Bridge/Symfony/DependencyInjection/CompilerPass/ConfigureDatabasesCompilerPass.php
src/Bridge/Symfony/Serializer/Normalizer/LocalizingNormalizer.php
tests/functional/site/config/packages/yassg_databases.yaml
tests/functional/site/content/products/nested/another.en.yaml
tests/functional/site/content/products/test1.en.yaml
tests/functional/site/content/products/test2.en.yaml
tests/functional/site/templates/pages/homepage.html.twig
tests/functional/site/templates/pages/index.html.twig

Allow model properties to be marked with an `Localized` attribute, meaning it's contextual and will be set according to current locale.

feat: localizable properties support

---

src/Bridge/Symfony/DependencyInjection/CompilerPass/ConfigureDatabasesCompilerPass.php
src/Bridge/Symfony/Serializer/Normalizer/LocalizingNormalizer.php

fix: localizing normalizer wiring

---

config/services.yaml
src/Bridge/Symfony/DependencyInjection/CompilerPass/ConfigureDatabasesCompilerPass.php
src/Bridge/Symfony/ExpressionLanguage/FunctionProvider.php
src/Bridge/Symfony/Serializer/Normalizer/ExpressionNormalizer.php
src/Bridge/Twig/Extension/DatabaseExtension.php
src/Database.php
src/Database/MemoryDatabase.php
src/DatabaseProvider.php
src/Storage/DenormalizingStorage.php
src/Storage/FilesystemStorage.php
src/Storage/MemoryStorage.php
src/StorageWithOptions.php
tests/functional/site/config/packages/yassg_databases.yaml
tests/functional/site/content/categories/category1.yaml
tests/functional/site/content/products/test2.en.yaml
tests/functional/site/src/Model/Category.php
tests/functional/site/templates/pages/homepage.html.twig
tests/functional/site/templates/pages/product.html.twig

feat: fetch by ID

---

psalm.xml.dist
src/Bridge/Symfony/Routing/Generator/FilenameUrlGenerator.php
src/Generator.php
tests/functional/init/vendor/sigwin/yassg/resources/Makefile
tests/functional/site/vendor/sigwin/yassg/resources/Makefile

feat: default to having a trailing slash when no index file

---

src/Generator.php

Thanks @thibault for helping with the debugging! :1st_place_medal:

fix: generate pages with trailing slash URLs

---

src/Bridge/Symfony/Serializer/Normalizer/LocalizingNormalizer.php
tests/functional/site/content/categories/category1.yaml
tests/functional/site/src/Model/Category.php

fix: skip NULL for localized properties

---

src/Storage/FilesystemStorage.php
tests/functional/site/config/packages/yassg_databases.yaml
tests/functional/site/content/categories/category1.yaml
tests/functional/site/content/overridden-categories/category1.yaml
tests/functional/site/content/overridden-products/nested/another.en.yaml
tests/functional/site/content/products/nested/another.en.yaml
tests/functional/site/src/Model/Category.php
tests/functional/site/src/Model/Product.php
tests/functional/site/templates/pages/homepage.html.twig
tests/functional/site/templates/pages/product.html.twig

feat: filesystem storage override

---

config/services.yaml
resources/Makefile
src/Bridge/Symfony/Routing/Generator/FilenameUrlGenerator.php
src/Bridge/Symfony/Routing/Loader/RouteLoader.php
src/Generator.php

--index-file doesn't apply in that case
Closes #111.

fix: routes not allowed to have pre-existing filenames, index.html always appended

---

src/Storage/FilesystemStorage.php
tests/functional/site/config/packages/yassg_databases.yaml

fix: correctly handle filesystem storage relative paths

---

src/Storage/DenormalizingStorage.php
src/Storage/FilesystemStorage.php
tests/functional/site/content/overridden-categories/category1.yaml
tests/functional/site/src/Model/Category.php

fix: recursive denormalizer

---

src/Database.php
src/Database/CachingDatabase.php
src/Database/MemoryDatabase.php
src/Storage.php
src/Storage/DenormalizingStorage.php
src/Storage/FilesystemStorage.php
src/Storage/MemoryStorage.php

feat: Database::has()

---

src/Bridge/Symfony/Routing/Generator/FilenameUrlGenerator.php
tests/functional/site/src/Bridge/Symfony/Routing/Generator/FilenameUrlGeneratorTest.php

fix: check if route exists before generating the URL

---

config/services.yaml
src/Bridge/Symfony/DependencyInjection/CompilerPass/InjectRouteVariablesCompilerPass.php
src/Bridge/Symfony/DependencyInjection/Configuration.php
src/Bridge/Symfony/DependencyInjection/KernelExtension.php
src/Bridge/Symfony/Kernel.php
src/Bridge/Symfony/Routing/Generator/GlobalVariableUrlGenerator.php

feat: route global variables

---

phpunit.xml.dist
src/BuildOptions.php
src/Generator.php
src/Location.php
src/Permutator.php
src/Route.php
tests/functional/site/fixtures/index.html
tests/functional/site/templates/pages/index.html.twig
tests/unit/GeneratorTest.php

feat: location value object

---

psalm.baseline.xml
tests/functional/site/content/categories/category2.yaml
tests/functional/site/content/products/test2.en.yaml
tests/functional/site/fixtures/en/example2/index.html
tests/functional/site/src/Model/Category.php

test: confirm nested localization fix

---

composer.json
config/services.yaml
tests/functional/site/content/articles/hello-world.md
tests/functional/site/fixtures/en/article/hello-world/index.html

feat: Markdown figure

---

composer.json
config/services.yaml
psalm.baseline.xml
src/Bridge/Symfony/Command/ValidateCommand.php
src/Bridge/Symfony/DependencyInjection/CompilerPass/ConfigureDatabasesCompilerPass.php
src/Context/LocaleContext.php
tests/functional/default.mk
tests/functional/site/config/packages/yassg_routes.yaml
tests/functional/site/src/Model/Article.php

feat: database validation
